---
# tasks file for mysql_db

- name: Install MySQL database
  yum:
    name: [mysql-server, mysql-devel]
    state: present


- name: create MySQL configuration file
  copy:
    content: |
      [client]
      user=root
      password="@targ8et"
    dest: "/etc/.my.cnf"

- name: Start MySQL Service
  service:
    name: mysqld
    state: started
    enabled: yes
